lab2/Entities/Entry.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace lab1.Entities
{
    public class Entry
    {
        // Composite key
        public int EntryPid { get; set; }
        public string UserName { get; set; }
        public DateTime ReportMonth { get; set; }
        public string ActivityCode { get; set; }

        // Fields
        private DateTime _Date;
        [DataType(DataType.Date)]
        public DateTime Date
        {
            get => _Date;
            set => _Date = value.Date;
        }
        public int Time { get; set; }
        public string Description { get; set; }

        // Foreign
        public string SubactivityCode { get; set; }

        // Parents
        public virtual Report Report { get; set; }
        public virtual Activity Activity { get; set; }
        public virtual Subcode Subcode { get; set; }

        // Concurrency
        public byte[] Timestamp { get; set; }
    }
}

lab2/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using lab1.Models;
using Microsoft.AspNetCore.Http;
using lab1.Entities;
using Microsoft.EntityFrameworkCore;
using lab1.debug;

namespace lab1.Controllers
{
    public class ActivityController : Controller
    {
        private readonly ILogger<ActivityController> _logger;

        public ActivityController(ILogger<ActivityController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult MyActivities()
        {
            var username = Request.Cookies["user"];
            if (username == null)
                return RedirectToAction("Login", "User");
            return View(new MyActivitiesModel(username));
        }

        [HttpGet]
        public IActionResult AddActivity()
        {
            return View(new AddActivityModel());
        }

        [HttpPost]
        public IActionResult PostAddActivity(AddActivityModel activityModel)
        {
            var username = Request.Cookies["user"];
            if (username == null)
                return RedirectToAction("Login", "User");
            var activity = activityModel.Activity;
            activity.ManagerName = username;
            try
            {
                using (var db = new LabContext())
                {
                    using (var trans = db.Database.BeginTransaction())
                    {
                        db.Add(activity);
                        db.SaveChanges();
                        db.AddRange(activityModel.SubcodesString.Split(',').Select(s => s.Trim()).Select(s => new Subcode { ActivityCode = activity.ActivityCode, SubactivityCode = s }));
                        db.SaveChanges();
                        trans.Commit();
                    }
                }
            }
            catch (DbUpdateException)
            {
                return RedirectToAction("MyActivities");
            }
            return RedirectToAction("MyActivities");
        }

        [HttpGet]
        public IActionResult ActivityInfo(string ActivityCode)
        {
            return View(new ActivityInfoModel(ActivityCode));
        }

        [HttpPost]
        public IActionResult UpdateTime(string ActivityCode, string UserName, DateTime ReportMonth, int Time)
        {
            AcceptedEntry acceptedEntry = new AcceptedEntry { ActivityCode = ActivityCode, UserName = UserName, ReportMonth = ReportMonth, Time = Time };
            using (var db = new LabContext())
            {
                var first = db.AcceptedEntries.Where(a => a.ActivityCode == ActivityCode && a.UserName == UserName && a.ReportMonth == ReportMonth).AsNoTracking().FirstOrDefault();
                if (first != null)
                    db.Update(acceptedEntry);
                else
                    db.Add(acceptedEntry);
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    foreach (var ce in ex.Entries)
                    {
                        var databaseValues = ce.GetDatabaseValues();
                        ce.OriginalValues.SetValues(databaseValues);
                    }
                }
            }
            return RedirectToAction("ActivityInfo", new { ActivityCode = ActivityCode });
        }

        [HttpPost]
        public IActionResult Deactivate(string ActivityCode)
        {
            Activity activity;
            using (var db = new LabContext())
            {
                activity = db.Activities.Where(a => a.ActivityCode == ActivityCode).FirstOrDefault();
                activity.Active = false;
                db.Update(activity);
                db.SaveChanges();
            }
            return RedirectToAction("MyActivities");
        }

        public JsonResult Subcodes(string ActivityCode)
        {
            Activity activity;
            using (var db = new LabContext())
            {
                activity = db.Activities.Include(a => a.Subcodes).Where(a => a.ActivityCode == ActivityCode).FirstOrDefault();
            }
            if (activity == null)
                return Json(null);
            return Json(activity.Subcodes.Select(s => s.SubactivityCode).Prepend("").ToList());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab2/Controllers/EntryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using lab1.Models;
using Microsoft.AspNetCore.Http;
using lab1.Entities;
using Microsoft.EntityFrameworkCore;
using lab1.Datetime;
using lab1.debug;

namespace lab1.Controllers
{
    public class EntryController : Controller
    {
        private readonly ILogger<EntryController> _logger;

        public EntryController(ILogger<EntryController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IActionResult MyEntries(DateTime? date)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");
            if (date.HasValue)
                return View(new MyEntriesModel(UserName, date.Value));
            else
                return View(new MyEntriesModel(UserName));
        }

        [HttpGet]
        public IActionResult EntryInfo(MyEntriesModel entryModel)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var entry = entryModel.SelectedEntry;
            entry.UserName = UserName;

            Entry e;
            using (var db = new LabContext())
            {
                e = db.Entries
                    .Where(e
                        => e.UserName == entry.UserName
                        && e.ReportMonth == entry.ReportMonth
                        && e.ActivityCode == entry.ActivityCode
                        && e.EntryPid == entry.EntryPid)
                    .Include(e => e.Activity)
                    .FirstOrDefault();
            }
            return View(e);
        }

        [HttpGet]
        public IActionResult ModifyEntry(MyEntriesModel entryModel, Entry MayBeEntry)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var entry = entryModel?.SelectedEntry ?? MayBeEntry;
            entry.UserName = UserName;

            Entry e;
            using (var db = new LabContext())
            {
                e = db.Entries
                    .Where(e
                        => e.UserName == entry.UserName
                        && e.ReportMonth == entry.ReportMonth
                        && e.ActivityCode == entry.ActivityCode
                        && e.EntryPid == entry.EntryPid)
                    .Include(e => e.Activity)
                    .FirstOrDefault();
            }
            return View("UpsertEntry", new UpsertEntryModel(e));
        }

        [HttpPost]
        public IActionResult PostModifyEntry(UpsertEntryModel entryModel)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var entry = entryModel.Entry;
            entry.UserName = UserName;
            entry.Activity = null;

            using (var db = new LabContext())
            {
                try
                {
                    db.Update(entry);
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    foreach (var ce in ex.Entries)
                    {
                        var databaseValues = ce.GetDatabaseValues();
                        ce.OriginalValues.SetValues(databaseValues);
                    }
                    var e = db.Entries.Where(e
                        => e.UserName == entry.UserName
                        && e.ReportMonth == entry.ReportMonth
                        && e.ActivityCode == entry.ActivityCode
                        && e.EntryPid == entry.EntryPid)
                        .FirstOrDefault();
                    return RedirectToAction("ModifyEntry", e);
                }
            }
            return RedirectToAction("MyEntries");
        }

        [HttpGet]
        public IActionResult AddEntry(DateTime? date)
        {
            return View("UpsertEntry", new UpsertEntryModel(date.HasValue ? date.Value : DateTime.Now));
        }

        [HttpPost]
        public IActionResult PostAddEntry(UpsertEntryModel entryModel)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var entry = entryModel.Entry;
            entry.UserName = UserName;

            var ReportMonth = entry.Date.Dayless();
            using (var db = new LabContext())
            {
                if (!db.Reports.Any(r => r.ReportMonth == ReportMonth && r.UserName == UserName))
                {
                    db.Add(new Report { ReportMonth = ReportMonth, UserName = UserName });
                    db.SaveChanges();
                }
            }
            entry.ReportMonth = ReportMonth;
            try
            {
                using (var db = new LabContext())
                {
                    db.Add(entry);
                    db.SaveChanges();
                }
            }
            catch (DbUpdateException e)
            {
                System.Console.WriteLine(e.ToString());
                return RedirectToAction("MyEntries");
            }
            return RedirectToAction("MyEntries");
        }

        [HttpPost]
        public IActionResult DeleteEntry(MyEntriesModel entriesModel)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var entry = entriesModel.SelectedEntry;
            entry.UserName = UserName;

            using (var db = new LabContext())
            {
                db.Remove(entry);
                db.SaveChanges();
            }

            return RedirectToAction("MyEntries");
        }

        [HttpGet]
        public IActionResult MonthlySummary(DateTime? dayless)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");
            var Date = dayless ?? DateTime.Now;

            return View(new MonthlySummaryModel(Date, UserName));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = System.Diagnostics.Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult LockMonth(DateTime dayless)
        {
            var UserName = Request.Cookies["user"];
            if (UserName == null)
                return RedirectToAction("Login", "User");

            var ReportMonth = dayless.Dayless();
            var report = new Report { ReportMonth = ReportMonth, UserName = UserName, Frozen = true };
            try
            {
                using (var db = new LabContext())
                {
                    db.Update(report);
                    db.SaveChanges();
                }
            }
            catch (DbUpdateException)
            { }
            return RedirectToAction("MonthlySummary", new { dayless = dayless });
        }
    }
}

lab2/Views/Entry/MyEntries.cshtml
@model MyEntriesModel
<div class="text-center">
    <form>
        <h1 class="display-4">Entries for
            <input type="date" name="date" value=@Model.Date.ToString("yyyy-MM-dd") onchange="this.form.submit()">
        </h1>
    </form>
    <table style="width: 100%">
        <tr>
            <th>Activity</th>
            <th>Subactivity</th>
            <th>Time [min]</th>
            <th>Options</th>
        </tr>
        <tr>
            <td colspan="4">
                <hr>
            </td>
        </tr>
        @foreach (var entry in Model.Entries)
        {
            Model.SelectedEntry = entry;
            <tr>
                <td>@entry.Activity.ActivityName</td>
                <td>@entry.SubactivityCode</td>
                <td>@entry.Time</td>
                <td style="font-size: 0">
                    <form action=@Url.Action("EntryInfo", "Entry") style="display: inline-block">
                        @Html.HiddenFor(m => m.SelectedEntry.UserName)
                        @Html.HiddenFor(m => m.SelectedEntry.ReportMonth)
                        @Html.HiddenFor(m => m.SelectedEntry.ActivityCode)
                        @Html.HiddenFor(m => m.SelectedEntry.EntryPid)
                        <button type="submit" style="display: inline-block; border: none; background-color: transparent">
                            <i class="material-icons">info</i>
                        </button>
                    </form>
                    @if (!Model.Report.Frozen)
                    {
                        <form action=@Url.Action("ModifyEntry", "Entry") style="display: inline-block">
                            @Html.HiddenFor(m => m.SelectedEntry.UserName)
                            @Html.HiddenFor(m => m.SelectedEntry.ReportMonth)
                            @Html.HiddenFor(m => m.SelectedEntry.ActivityCode)
                            @Html.HiddenFor(m => m.SelectedEntry.EntryPid)
                            <button style="display: inline-block; border: none; background-color: transparent">
                                <i class="material-icons">settings</i>
                            </button>
                        </form>
                        <form method="post" action=@Url.Action("DeleteEntry", "Entry") style="display: inline-block">
                            @Html.HiddenFor(m => m.SelectedEntry.UserName)
                            @Html.HiddenFor(m => m.SelectedEntry.ReportMonth)
                            @Html.HiddenFor(m => m.SelectedEntry.ActivityCode)
                            @Html.HiddenFor(m => m.SelectedEntry.EntryPid)
                            <button style="display: inline-block; border: none; background-color: transparent">
                                <i class="material-icons">delete</i>
                            </button>
                        </form>
                    }
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <hr>
                </td>
            </tr>
        }
        @if (!(Model.Report?.Frozen ?? false))
        {
            <tr style="font-size: 0">
                <td colspan=6>
                    <button style="display: inline-block; border: none; background-color: transparent"
                    onclick="window.location.href = '@Url.Action("AddEntry", new { date = Model.Date.ToString("yyyy-MM-dd") })'">
                        <i class="material-icons">add_circle</i>
                    </button>
                </td>
            </tr>
        }
    </table>
    <label>Total time: @Model.TotalTime</label>
</div>

lab2/Views/Entry/UpsertEntry.cshtml
@model UpsertEntryModel
<div class="text-center">
    <p>
        @if (Model.Insert)
        {
            @:Add new entry.
        }
        else
        {
            @:Modify entry.
        }
    </p>
    @using (Html.BeginForm(Model.Insert ? "PostAddEntry" : "PostModifyEntry", "Entry", null, FormMethod.Post, true,
    null))
    {
        if (!Model.Insert)
        {
            @:@Html.HiddenFor(m => m.Entry.EntryPid)
            @:@Html.HiddenFor(m => m.Entry.ActivityCode)
            @:@Html.HiddenFor(m => m.Entry.Date)
            @:@Html.HiddenFor(m => m.Entry.ReportMonth)
        }
            <table width="100%">
                <tr>
                    <td>Date</td>
                    <td>@(
                Model.Insert
                ? Html.EditorFor(m => m.Entry.Date)
                : Html.DisplayFor(m => m.Entry.Date)
                )</td>
                </tr>
                <tr>
                    <td>Project</td>
                    <td>
                    @if (Model.Insert)
                    {
                        @Html.DropDownListFor(m => m.Entry.ActivityCode, Model.Activities)
                    }
                    else
                    {
                        @Html.DisplayFor(m => m.Entry.Activity.ActivityName)
                        @Html.HiddenFor(m => m.Entry.Activity.ActivityName)
                    }
                    </td>
                </tr>
                <tr>
                    <td>Time</td>
                    <td>@Html.EditorFor(m => m.Entry.Time)</td>
                </tr>
                <tr>
                    <td>Subcode</td>
                    <td>
                    @if (Model.Insert)
                    {
                        @Html.DropDownListFor(m => m.Entry.SubactivityCode, new List<SelectListItem>())
                    }
                    else
                    {
                        @Html.DropDownListFor(m => m.Entry.SubactivityCode, Model.Subcodes)
                    }
                    </td>
                </tr>
                <tr>
                    <td>Description</td>
                    <td>@Html.EditorFor(m => m.Entry.Description)</td>
                </tr>
            </table>
            <input type="submit">
    }
    <input type="button" value="Cancel" onclick="history.back()">
</div>
@if (Model.Insert)
{
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script type="text/javascript">
            jQuery(document).ready(function () {
                updateSubcodes();
            })

            $("#Entry_ActivityCode").change(function () {
                updateSubcodes();
            });

            var updateSubcodes = function () {
                $.ajax({
                    url: '@Url.Action("Subcodes","Activity")',
                    type: 'GET',
                    data: {
                        ActivityCode: $('#Entry_ActivityCode').val(),
                    },
                    success: function (data) {
                        $('#Entry_SubactivityCode').find('option').remove()
                        $(data).each(
                            function (index, subcode) {
                                $('#Entry_SubactivityCode').append('<option>' + subcode + '</option>')
                            }
                        );
                    },
                    error: function () { }
                });
            }
        </script>
}